version: '3'
services:
  multicorn:
    build: ./
    image: multicorn:latest
    container_name: multicorn
    hostname: multicorn
    environment:
      - PGMAJOR=13
      - CLOUDSMITH_TOKEN=${CLOUDSMITH_TOKEN}
    volumes:
      - ./:/cloudsmith_fdw
    entrypoint: /cloudsmith_fdw/entrypoint.sh
